version: '3.7'
services:
  petdb:
    build: ./mysql
    image: mysql:5.7
    ports:
    - target: 3306
      published: 3306
      protocol: tcp
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DB=petclinic
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
    volumes:
    - type: volume
      source: petdb-volume
      target: /var/lib/mysql
  backend:
    build: ./back-end
    image: backend
    ports:
    - target: 9966
      published: 9966
      protocol: tcp
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://petdb:3306/petclinic?useUnicode=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - petdb 
  frontend:
    build: ./front-end
    image: frontend
    ports:
    - target: 4200
      published: 4200
      protocol: tcp
    depends_on:
      - backend
  nginx:
    build: ./nginx
    image: petnginx
    ports:
    - target: 80
      published: 80
      protocol: tcp
    depends_on:
    - backend
    - frontend

volumes:
  petdb-volume:
